### ISSUE TITLE
v2.3.0-rc2 转表错误

### ISSUE THREAD

**Issue by vividkings** [xresloader/xresconv-gui#12]
ReferenceError: log is not defined
    at run_one_child_process (F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:1785:13)
    at run_all_cmds (F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:1877:11)
    at new Promise (<anonymous>)
    at F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:2036:20

**Comment by owent** [comment]
https://github.com/xresloader/xresconv-gui/releases/tag/v2.3.0-rc3
感谢反馈，已修复
