### ISSUE TITLE
mac osx 无法开启

### ISSUE THREAD

**Issue by yingnierxiao** [xresloader/xresconv-gui#2]
Uncaught Exception:
Error: Image could not be created from /private/var/folders/sd/d3dc79797rg6t_zhnhsddm880000gp/T/AppTranslocation/727DA5E4-B55A-4CE1-A27D-337632417A91/d/xresconv-gui.app/Contents/Resources/app.asar/src/../doc/logo.ico
    at App.createWindow (/private/var/folders/sd/d3dc79797rg6t_zhnhsddm880000gp/T/AppTranslocation/727DA5E4-B55A-4CE1-A27D-337632417A91/d/xresconv-gui.app/Contents/Resources/app.asar/src/setup.js:41:9)
    at App.emit (events.js:223:5)

**Comment by owent** [comment]
@yingnierxiao 请问下你是直接下载的发布包打开报这个错吗？还是yarn执行的时候？

**Comment by yingnierxiao** [comment]
直接下载出错的

**Comment by owent** [comment]
@yingnierxiao https://github.com/xresloader/xresconv-gui/releases/tag/v2.2.4
已修复
