### ISSUE TITLE
输出日志

### ISSUE THREAD

**Issue by vividkings** [xresloader/xresconv-gui#7]
调用log函数、输出到console的同时写入到日志文件，方便调试

**Comment by owent** [comment]
Done. v2.3.0-rc2 版本开始支持。
增加了启动选项 `--log-configure <log设置文件 json文件名>` : 设置额外的log配置。设置文件结构请参见: https://www.npmjs.com/package/log4js
默认使用 

```json
{
  "appenders": {
    "app": {
      "type": "file",
      "filename": "xresconv-gui.info.log",
      "maxLogSize": 10485760,
      "numBackups": 3
    },
    "errorFile": {
      "type": "file",
      "filename": "xresconv-gui.error.log"
    },
    "errors": {
      "type": "logLevelFilter",
      "level": "ERROR",
      "appender": "errorFile"
    }
  },
  "categories": {
    "default": { "appenders": [ "app", "errors" ], "level": "DEBUG" }
  }
}
```

**Comment by vividkings** [comment]
更换v2.3.0-rc2后 转表错误
[2021-09-01T15:08:52.396] [ERROR] CONV - [CONV]: <pre class="conv_pre_default conv_pre_error">ReferenceError: log is not defined
    at run_one_child_process (F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:1785:13)
    at run_all_cmds (F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:1877:11)
    at new Promise (&lt;anonymous&gt;)
    at F:\Code\CppProject\server_bin\designer_data\Table\xresloader\xresconv-gui-win32-x64\resources\app.asar\src\main.js:2036:20</pre>
